# Generated by Django 5.1 on 2024-09-02 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsreporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='allowed_courses',
            field=models.ManyToManyField(to='lmsreporting.course'),
        ),
        migrations.AlterField(
            model_name='module',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='module',
            name='credit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='module',
            name='registered_students',
            field=models.ManyToManyField(blank=True, related_name='registered_modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
