# Generated by Django 4.2.15 on 2024-08-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsreporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='date_subimtted',
            new_name='date_submitted',
        ),
    ]
